// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: weather/forecast/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ShortForecastRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ShortForecastRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShortForecastRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ShortForecastRequestMultiError, or nil if none found.
func (m *ShortForecastRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ShortForecastRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Latitude

	// no validation rules for Longitude

	if len(errors) > 0 {
		return ShortForecastRequestMultiError(errors)
	}

	return nil
}

// ShortForecastRequestMultiError is an error wrapping multiple validation
// errors returned by ShortForecastRequest.ValidateAll() if the designated
// constraints aren't met.
type ShortForecastRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShortForecastRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShortForecastRequestMultiError) AllErrors() []error { return m }

// ShortForecastRequestValidationError is the validation error returned by
// ShortForecastRequest.Validate if the designated constraints aren't met.
type ShortForecastRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShortForecastRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShortForecastRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShortForecastRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShortForecastRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShortForecastRequestValidationError) ErrorName() string {
	return "ShortForecastRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ShortForecastRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShortForecastRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShortForecastRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShortForecastRequestValidationError{}

// Validate checks the field values on ShortForecastResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ShortForecastResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShortForecastResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ShortForecastResponseMultiError, or nil if none found.
func (m *ShortForecastResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ShortForecastResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ShortForecast

	// no validation rules for Characterization

	if len(errors) > 0 {
		return ShortForecastResponseMultiError(errors)
	}

	return nil
}

// ShortForecastResponseMultiError is an error wrapping multiple validation
// errors returned by ShortForecastResponse.ValidateAll() if the designated
// constraints aren't met.
type ShortForecastResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShortForecastResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShortForecastResponseMultiError) AllErrors() []error { return m }

// ShortForecastResponseValidationError is the validation error returned by
// ShortForecastResponse.Validate if the designated constraints aren't met.
type ShortForecastResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShortForecastResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShortForecastResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShortForecastResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShortForecastResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShortForecastResponseValidationError) ErrorName() string {
	return "ShortForecastResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ShortForecastResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShortForecastResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShortForecastResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShortForecastResponseValidationError{}
